### ISSUE TITLE
Observatory scene not showing correctly & All bodies visible in Tracking Station upon first discovery

### ISSUE THREAD

**Issue by DavidChen-cxl** [JPLRepo/ResearchBodies#50]
Hello, I'm the same player posting in the forum about this issue. 

I'm using KSP 1.8.1 with Researchbodies 1.11.0.0. This is the list of mods and modules recorded in the `persistent.sfs` savefile. I will attach the save and .ckan mod pack. 

`LoaderInfo
	{
		ModuleManager v4.1.3.0 = True
                ClickThroughBlocker v0.1.9.5 / v1.0.0.0 = True
		aaa_Toolbar v1.8.0.5 = True
		ToolbarControl v0.1.9.4 / v1.0.0.0 = True
		BetterTimeWarp v2.3.12.5 = True
		ContractConfigurator v1.0.0.0 / v1.28.0 = True
		CustomBarnKit v1.1.20.0 = True
		DistantObject v1.9.1.29406 = True
		EasyVesselSwitch v2.1.7366.39779 / v2.1 for KSP v1.* = True
		KSPDev_Utils.2.0 v2.0.7231.38433 / v2.0 for KSP v1.8+ = True
		Atmosphere v1.8.0.2 = True
		CelestialShadows v1.8.0.2 = True
		CityLights v1.8.0.2 = True
		EVEManager v1.8.0.2 = True
		PartFX v1.8.0.2 = True
		PQSManager v1.8.0.2 = True
		ShaderLoader v1.8.0.2 = True
		Terrain v1.8.0.2 = True
		TextureConfig v1.8.0.2 = True
		Utils v1.8.0.2 = True
		_BuildManager v1.8.0.2 = True
		HotSpot v0.8.0.0 / v0.8.0 = True
		KerbalJointReinforcement v3.5.1.0 = True
		Kopernicus.Parser v1.0.0.0 = True
		ModularFlightIntegrator v1.0.0.0 / v1.2.7.0 = True
		Kopernicus v1.0.0.0 = True
		MechJeb2 v2.5.1.0 / v / v2.9.2.0 = True
		PlanetShine v0.2.6.1 = True
		PreciseNode v1.2.11.0 / v1.2.4.0 = True
		ProgressiveCBMaps v0.1.29.0 = True
		ResearchBodies v1.11.0.0 = True
		scatterer v0.0.0.0 = True
		Sigma88LoadingScreens v0.3.3.0 = True
		TransferWindowPlanner v1.7.2.0 = True
		ZeroMiniAVC v1.1.0.1 = True
		000_ClickThroughBlocker = True
		000_Toolbar = True
		001_ToolbarControl = True
		BetterTimeWarp = True
		CommunityResourcePack = True
		ContractConfigurator = True
		CTTP = True
		CustomBarnKit = True
		DistantObject = True
		EasyVesselSwitch = True
		EnvironmentalVisualEnhancements = True
		HotSpot = True
		KerbalJointReinforcement = True
		Kopernicus = True
		MechJeb2 = True
		ModularFlightIntegrator = True
		OPM = True
		PlanetShine = True
		PreciseNode = True
		REPOSoftTech = True
		scatterer = True
		Sigma = True
		StockVisualEnhancements = True
		TriggerTech = True
		ZeroMiniAVC = True
		ModuleManager.4.1.3.dll = True
		ModuleManager.ConfigCache = True
		ModuleManager.ConfigSHA = True
		ModuleManager.Physics = True
		ModuleManager.TechTree = True
		toolbar-settings.dat = True
	}`

Two problems suddenly showed up at the same time, right after the "search the skies" contract found the first body (Sarnus in this save). 

![1](https://user-images.githubusercontent.com/62462818/80454436-a0715580-895c-11ea-9f44-08a458403b52.JPG)

The first problem is that, all the hidden bodies became visible in the tracking station. However, according to the save file, only the Sun, Kerbin, the Mun and Sarnus had been discovered at that time. 

![2](https://user-images.githubusercontent.com/62462818/80454504-bd0d8d80-895c-11ea-918a-4ca36ce59e79.JPG)

Secondly, after returning to the "Spacecenter" scene from Tracking Station, if I click on the Observatory, the scene does not change; only the Observatory soundtrack plays. I can move my perspective around the space center, but I can no longer click on anything, like other buildings and the exit button. 

![3](https://user-images.githubusercontent.com/62462818/80454630-ef1eef80-895c-11ea-8163-de592014a726.JPG)

[KSP.log](https://github.com/JPLRepo/ResearchBodies/files/4543719/KSP.log)
[mod list.zip](https://github.com/JPLRepo/ResearchBodies/files/4543775/mod.list.zip)
[Breaking Ground.zip](https://github.com/JPLRepo/ResearchBodies/files/4543725/Breaking.Ground.zip)

**Comment by Miruzuki** [comment]
Having exactly the same issue here.

**Comment by ThePizza1k** [comment]
I am also experiencing the Observatory issue.

**Comment by Lucaspec72** [comment]
I am pretty sure i'm also having the same issue, it worked fine until a few hours ago

**Comment by JPLRepo** [comment]
Saying you have an issue doesn't really help me all that much for several reasons:
You are all playing the game with many mods installed. I can't tell if your problems are my mod or another mod as you haven't supplied logs.
I can't reproduce your bug because you either have too many mods installed (which I would have to install) or you haven't supplied me with clear reproduction steps.

The one user who did supply some information, the log supplied has no errors in it related to this mod. and I don't think is an actual log recording when the error occurred or when you try to enter the observatory or map mode with the problem. IF it was then there would be log entries from this mod that might indicate what is going wrong.

I've been unable to reproduce the bug myself.
I need more information such as log files when the error occurs, not just a KSP start up log.

**Comment by CptKermit** [comment]
I've had this issue for awhile now and have discovered I can no longer play KSP without Research Bodies. So, I've spent the last four days trying to track this issue down. I finally did it. :)
I'm guessing all of you are running Galileo's Planet pack as a secondary with Galileo's Outer Planets Mod too. In Each of the planet packs he has a ResearchBodies.cfg file. The first part of each of those files is what makes his planet packs fully compatible with Research Bodies but the second half gives the telescopes some upgrades so they can see far enough to discover the additional planets. I noticed that there where no scope upgrades in my game so I went looking for whatever I might find. I'm not an avid modder so I can't say positively that they conflicted, but I saw no need for both sets, so I deleted the upgrades in the OPM mod file because the ones in GPP are better/farther and the issue went away. 

Delete the **bold** text and save.

RESEARCHBODIES
{
	loadAs = mod
	name = OPM
	ONDISCOVERY
	{
		Sarnus = #autoLOC_RBodies_discovery_Sarnus
		Hale = #autoLOC_RBodies_discovery_Hale
		Ovok = #autoLOC_RBodies_discovery_Ovok
		Slate = #autoLOC_RBodies_discovery_Slate
		Tekto = #autoLOC_RBodies_discovery_Tekto
		Eeloo = #autoLOC_RBodies_discovery_Eeloo2
		Urlum = #autoLOC_RBodies_discovery_Urlum
		Polta = #autoLOC_RBodies_discovery_Polta
		Priax = #autoLOC_RBodies_discovery_Priax
		Wal = #autoLOC_RBodies_discovery_Wal
		Tal = #autoLOC_RBodies_discovery_Tal
		Neidon = #autoLOC_RBodies_discovery_Neidon
		Thatmo = #autoLOC_RBodies_discovery_Thatmo
		Nissee = #autoLOC_RBodies_discovery_Nissee
		Plock = #autoLOC_RBodies_discovery_Plock
		Karen = #autoLOC_RBodies_discovery_Karen
	}
	IGNORE
	{
		body = Sarnus
	}
	IGNORELEVELS
	{
		// body = easy normal medium hard
		Sarnus = true true true true
		Hale = false false false false
		Ovok = false false false false
		Slate = false false false false
		Tekto = false false false false
		Eeloo = true true false false
		Polta = false false false false
		Priax = false false false false
		Wal = false false false false
		Tal = false false false false
		Neidon = false false false false
		Thatmo = false false false false
		Nissee = false false false false
		Plock = false false false false
		Karen = false false false false
	}
}

**@PART[TrackBodiesTelescope]:NEEDS[OPM&!GPP]
{
	@MODULE[ModuleTrackBodies]
	{
		showUpgradesInModuleInfo = true
		UPGRADES
		{
			UPGRADE
			{
				name__ = RB_Upgrade
				difficulty = 6
				scienceReward = 25
				minAltitude = 500000
				maxTrackDistance = 9E+11
				electricChargeRequest = 15
				description__ = Upgrade for ResearchBodies Telescope.
				
			}
		}
	}
}

PARTUPGRADE:NEEDS[OPM&!GPP]
{
	name = RB_Upgrade
	partIcon = TrackBodiesTelescope
	techRequired = largeUnmanned
	title = Discovery Telescope Upgrade
	basicInfo = Upgrade ResearchBodies Telescope
	description = Increases the telescope's range to 900 Gm, roughly 22.5x its original range and nearly 2x Plock's distance from The Sun. The minimum required operating altitude is also raised to 500 km for reduced chance of glare from th body the telescope is orbiting.
	entryCost = 25000
}**

**Comment by JPLRepo** [comment]
That file is part of the OPM mod. not this mod.
